module.exports = {
    "env": {
      "es6": true,
      "node": true
    },
    "extends": [
      "eslint:recommended"
    ],
    "parserOptions": {
      "ecmaVersion": 2020,
      "sourceType": "module"
    },
    "rules": {
      "array-bracket-spacing": ["error", "never"],
      "arrow-body-style": ["warn", "as-needed"],
      "arrow-parens": ["warn", "as-needed"],
      "arrow-spacing": "warn",
      "block-spacing": "warn",
      "camelcase": "warn",
      "class-methods-use-this": "warn",
      "comma-spacing": "warn",
      "curly": ["warn", "multi"],
      "dot-notation": "error",
      "eqeqeq": ["warn", "always"],
      "func-call-spacing": ["warn", "never"],
      "func-name-matching": "error",
      "generator-star-spacing": "warn",
      "indent": ["error", 4, { "SwitchCase": 1 }],
      "key-spacing": "warn",
      "linebreak-style": ["error", "unix"],
      "max-depth": "warn",
      "multiline-ternary": ["warn", "never"],
      "no-console": ["warn", { "allow": ["warn", "info", "error"] }],
      "no-duplicate-imports": "error",
      "no-else-return": "warn",
      "no-extra-bind": "error",
      "no-extra-parens": "error",
      "no-floating-decimal": "error",
      "no-lonely-if": "warn",
      "no-magic-numbers": ["warn", { "ignore": [1], "ignoreArrayIndexes": true }],
      "no-multi-spaces": "error",
      "no-multiple-empty-lines": ["warn", { "max": 1 }],
      "no-nested-ternary": "error",
      "no-new-object": "error",
      "no-return-await": "error",
      "no-throw-literal": "error",
      "no-trailing-spaces": "error",
      "no-undef-init": "error",
      "no-useless-constructor": "warn",
      "no-useless-rename": "error",
      "no-useless-return": "error",
      "no-var": "warn",
      "object-curly-spacing": ["warn", "always"],
      "object-shorthand": "warn",
      "padded-blocks": ["warn", "never"],
      "prefer-arrow-callback": "warn",
      "prefer-const": "warn",
      "prefer-exponentiation-operator": "warn",
      "prefer-numeric-literals": "warn",
      "prefer-rest-params": "warn",
      "prefer-spread": "warn",
      "prefer-template": "error",
      "quote-props": ["warn", "as-needed"],
      "quotes": ["error", "single"],
      "require-await": "warn",
      "rest-spread-spacing": "error",
      "semi": ["error", "never"],
      "spaced-comment": ["warn", "always"],
      "strict": ["error", "never"],
      "template-curly-spacing": "warn",
      "yield-star-spacing": "warn",
      "yoda": "warn"
    },
    "globals": {
      "PRODUCTION": true
    }
}